# Generated by Django 4.2.7 on 2026-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
